version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.20.0
    
    working_directory: ~/repo
    
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      
      - run:
          name: Install Dependencies
          command: yarn install
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      # Run tests
      - run:
          name: Run Tests
          command: yarn test
      
      # Build the project
      - run:
          name: Build
          command: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build 