name: run-test-unit

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  test-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build to run test unit (Node ${{ matrix.node-version }})
        uses: docker/build-push-action@v4
        with:
          context: .
          file: node-${{ matrix.node-version }}.dockerfile
          push: false
          tags: steem-js:node${{ matrix.node-version }} 